---
slug: :message_retweet
depends:
  mikutter: '5.0'
  plugin:
    - message_detail_view
    - skin
    - gtk3
    - twitter
version: '2.0'
author: toshi_a
name: ReTweet
description: "リツイートの表示に関するプラグイン"
